gen-menu-doc: Force utf8 encoding when reading ids.tbl
On Windows, there was a build failure because this outdated operating
system still uses their proprietary 1980s-era CP1252 code page by
default instead of proper Unicode.

```
python3 tools/gen-menu-doc.py --model dm32
Reading src/ids.tbl �
Traceback (most recent call last):
  File "D:/a/db48x/db48x/tools/gen-menu-doc.py", line 665, in <module>
    main()
    ~~~~^^
  File "D:/a/db48x/db48x/tools/gen-menu-doc.py", line 585, in main
    name_map = parse_ids_tbl(IDS_TBL)
  File "D:/a/db48x/db48x/tools/gen-menu-doc.py", line 131, in parse_ids_tbl
    text = strip_c_comments(path.read_text())
                            ~~~~~~~~~~~~~~^^
  File "D:/a/_temp/msys64/mingw64/lib/python3.14/pathlib/__init__.py", line 788, in read_text
    return f.read()
           ~~~~~~^^
  File "D:/a/_temp/msys64/mingw64/lib/python3.14/encodings/cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
           ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 8649: character maps to <undefined>
Reading src/ids.tbl �
Traceback (most recent call last):
  File "D:/a/db48x/db48x/tools/gen-menu-doc.py", line 665, in <module>
    main()
    ~~~~^^
  File "D:/a/db48x/db48x/tools/gen-menu-doc.py", line 585, in main
    name_map = parse_ids_tbl(IDS_TBL)
  File "D:/a/db48x/db48x/tools/gen-menu-doc.py", line 131, in parse_ids_tbl
    text = strip_c_comments(path.read_text())
                            ~~~~~~~~~~~~~~^^
  File "D:/a/_temp/msys64/mingw64/lib/python3.14/pathlib/__init__.py", line 788, in read_text
    return f.read()
           ~~~~~~^^
  File "D:/a/_temp/msys64/mingw64/lib/python3.14/encodings/cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
           ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 8649: character maps to <undefined>
mingw32-make[1]: *** [Makefile:416: doc/8-menus-tree-dm42.md] Error 1
mingw32-make: *** [Makefile:315: sim-release] Error 2
Error: Process completed with exit code 2.
```

Signed-off-by: Christophe de Dinechin <christophe@dinechin.org>